spring.application.name=LittleLemon
spring.datasource.url=jdbc:mysql://localhost:3306/llcaffedb
spring.datasource.username=root
spring.datasource.password=ROOTtoor
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.root=INFO
logging.level.com.LittleLemon.dto=DEBUG
logging.file.path=logs/
logging.file.name=app.log

